### ISSUE TITLE
[eslint-plugin] Update eslint rule for checking Module Lifecycle decorator

### ISSUE THREAD

**Issue by lokshunhung** [pinnacle0/frontend-libraries#2]
# Reason for change

The `@Lifecycle()` decorator is [removed in recent version of core-native](https://github.com/dionshihk/core-native-project/blob/580b6e83851c6ebc3df52764e9043c0c71a8f88d/src/platform/ModuleProxy.tsx), and the TypeScript `override` keyword is preferred.

So it no longer make sense to keep code to check for `Module` class `@Lifecycle()` decorator in the ESLint rule [module-class-method-decorators](https://github.com/pinnacle0/frontend-libraries/blob/8551c39ac0ef5c4a8b9a22d30a85a1fc80b36f8e/packages/eslint-plugin/src/rules/module-class-method-decorators.ts).

# Current behaviour

ESLint rule checks for `@Lifecycle()` decorator.

# Expected behaviour

ESLint rule no longer checks for `@Lifecycle()` decorator.

**Comment by dionshihk** [comment]
Thanks. We will update this rule soon!
